name: Linux - Build CLI

on:
  workflow_dispatch:
  pull_request:

env:
  DOCKER_REPO_HIVE_CLI: ${{ vars.DOCKER_REPO_HIVE_CLI }}

jobs:
  build-linux-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/Hive.CLI/

      - name: Build
        run: dotnet build -c Release --no-restore

  build-release-linux-cli-docker-image:
    needs: build-linux-cli
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/github-script@v6
        id: img-name
        with:
          script: |
            const imageName = process.env.DOCKER_REPO_HIVE_CLI + ':' + context.ref_name + '.' + context.sha

            core.setOutput('IMAGE_NAME', imageName)

      - name: Build Docker image
        run: docker build --file ./src/Hive.CLI/Dockerfile --tag ${{ steps.img-name.outputs.IMAGE_NAME }} .

      - name: Push Docker image
        run: docker push ${{ steps.img-name.outputs.IMAGE_NAME }}
